# $FreeBSD$
# All the dts files for allwinner systems we support.
DTS=	\
	bananapi.dts \
	cubieboard.dts \
	cubieboard2.dts \
	hummingbird-a31.dts \
	olimex-a20-som-evb.dts \
	olinuxino-lime.dts

.include <bsd.dtb.mk>
